[package]
name = "jiter"
version = "0.0.2"
edition = "2021"
description = "Iterable JSON parser"
readme = "README.md"
license = "MIT"
keywords = ["JSON", "parsing", "deserialization", "iter"]
categories = ["parser-implementations", "parsing"]
homepage = "https://github.com/pydantic/jiter/"
repository = "https://github.com/pydantic/jiter/"

[dependencies]
indexmap = "2.0.0"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.0"
num-bigint = "0.4.3"
num-traits = "0.2.16"
ahash = "0.8.0"
smallvec = "1.11.0"
pyo3 = { version = "0.19.2", features = ["num-bigint"], optional = true }
lexical-core = { version = "0.8.5", features = ["format"] }

[features]
python = ["dep:pyo3"]

[dev-dependencies]
paste = "1.0.7"
serde_json = {version = "1.0.87", features = ["preserve_order", "arbitrary_precision", "float_roundtrip"]}
serde = "1.0.147"
pyo3 = { version = "0.19.2", features = ["num-bigint", "auto-initialize"] }

[profile.bench]
debug = true
lto = true
opt-level = 3
codegen-units = 1

[[bench]]
name = "python_parse"
required-features = ["python"]
